apiVersion: v1
kind: Pod
metadata:
  name: network-troubleshooting
  namespace: default
spec:
  containers:
    - name: net-tools
      image: repo/[nombre de la imagen:tag] 
      command: ["/bin/sh"]
      args: ["-c", "sleep 3600"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 1000
  restartPolicy: Never
